### ISSUE TITLE
css style not correct?

### ISSUE THREAD

**Issue by YichaoOU** [romanonatacha/dash_trich_components#29]
Hello,

I'm trying to replicate the `Side Bar` example. But using the same code, and the css provided in the bottom of the page, this is what I got:

![image](https://user-images.githubusercontent.com/19987406/123873180-b92c2100-d8fb-11eb-8062-18e30f4e18b3.png)
I guess I didn't have the correct CSS?

Thanks,
Yichao

**Comment by romanonatacha** [comment]
Hey @YichaoOU, I couldn't get your question, what css are you referring to? Because there is not css for the sidebar component in the doc, I'm wondering if you copied the css from the other component at the bottom of the page.
Can you paste the css here, please?

But you don't need to use any css to implement the component, you need to pass the arguments with the colors you wanna use:
![image](https://user-images.githubusercontent.com/33462970/123883065-87788180-d91e-11eb-8cd2-ea98f8c2bbc0.png)

**Comment by kaburelabs** [comment]
Hey @YichaoOU, on the linked repository I have the sidebar implemented, and as you can see it do not have extra arguments and is working well 

![image](https://user-images.githubusercontent.com/24701735/123884562-e1c71180-d921-11eb-9624-ce5b454684df.png)

https://github.com/kaburelabs/marketing-app-prototype

**Comment by YichaoOU** [comment]
Thank you so much for the quick reply. I found the reason was `style={'position': 'relative'}`. If I remove it, like in @kaburelabs example code, then everything is fine.  I'm not good at CSS, so I can't really explain why.

![image](https://user-images.githubusercontent.com/19987406/123901312-53a65780-d930-11eb-8fad-130de04b6b7f.png)

**Comment by romanonatacha** [comment]
@YichaoOU You are right, this style should not be on the documentation, just updated the docs, and I'll close this issue.
