### ISSUE TITLE
[Sidebar] icons not showing

### ISSUE THREAD

**Issue by jeroen84** [romanonatacha/dash_trich_components#3]
Hi, first of all thank you for sharing the components you built for Dash. I see the potential for using this in one of my dashboards.

First thing I have tried is using the sidebar. Following the example in the documentation, I ended up with a dashboard whereby the icons of the sidebar are missing. It seems like there is no reference to the Font Awesome CSS library in the `dash_trich_components` code. After adding a reference to the Font Awesome Bootstrap CDN (https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css) to the `external_stylesheets` array of the Dash class (couldn't find a  >= v5.0 CDN quickly), **and** adjusting the `icon` reference to Font Awesome v4.7.0 style, the icons appear.

Is this the right approach?

Running version `0.0.8` of `dash_trich_components`, and version `1.12.0` of Dash.

**Comment by romanonatacha** [comment]
hello, thanks for your comment.
I was having issues with font awesome, on the last release i had made some adjusts, and maybe is the reason of font awesome is not being included, what i'm still thinking if it is the best, because if the library includes don't awesome, maybe it could break the layout of the user project, because he might be using a different version and the icons are different.
so i think for now I will include to the documentation about font awesome and this about a best improvement.

thanks

**Comment by romanonatacha** [comment]
hello, thanks for your comment.
I was having issues with font awesome, on the last release i had made some adjusts, and maybe is the reason of font awesome is not being included, what i'm still thinking if it is the best, because if the library includes don't awesome, maybe it could break the layout of the user project, because he might be using a different version and the icons are different.
so i think for now I will include to the documentation about font awesome and this about a best improvement.

thanks
